spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: root
#config Redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

logging:
  path: d:\\logs\java_webapi
